// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"os"
)

// Injectors from wire.go:

func InitApp() App {
	int2 := _wireIntValue
	foo := NewFoo(int2)
	reader := _wireFileValue
	app := NewApp(foo, reader)
	return app
}

var (
	_wireIntValue  = 12
	_wireFileValue = os.Stdin
)
