// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-app/third/dependency_injection/wire/example-project/internal/config"
	"go-app/third/dependency_injection/wire/example-project/internal/log"
	"go-app/third/dependency_injection/wire/example-project/internal/server"
)

// Injectors from wire.go:

func wireApp(configConfig *config.Config, logger *config.Logger, configServer *config.Server) (*App, func(), error) {
	sugaredLogger := log.NewLogger(logger)
	httpServer := server.NewHTTPServer(configServer)
	app := newApp(configConfig, sugaredLogger, httpServer)
	return app, func() {
	}, nil
}
