// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-app/third/dependency_injection/wire/example-interface/internal/config"
	"go-app/third/dependency_injection/wire/example-interface/internal/dao"
	"go-app/third/dependency_injection/wire/example-interface/internal/db"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	dbDB, err := db.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	daoDao := dao.NewDao(dbDB)
	app, err := NewApp(daoDao)
	if err != nil {
		return nil, err
	}
	return app, nil
}
